language: node_js

sudo: false

node_js:
  - 10
  - 12

before_install:
  - npm install -g npm@7

script:
  - npm --version
  - npm run build
  - npm run test-unit-travis || travis_terminate 1
  - npm run lint
  - npm run check-packages

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      node: 12
      branch: main
